use_frameworks!

platform :ios, '9.0'

target 'CNLiveEnvironmentConfiguration_Example' do
  pod 'CNLiveEnvironmentConfiguration', :path => '../'

  target 'CNLiveEnvironmentConfiguration_Tests' do
    inherit! :search_paths

    
  end
end
